on:
  workflow_dispatch:

name: 07-test-tidyverse

jobs:
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::tidyverse
            any::quantmod

      - name: print-message
        run:  Rscript scripts/tidyverse.R
