# 1 - Events
on:
  workflow_dispatch:
  #puch:
  # branches: main
  # schedule:
  #   - cron:  "*/5 * * * *"


# 2 - Jobs
name: 07-test-tidyverse
jobs:
  run-rmd-script:
  # 2a - The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

  # 2b - Load repo and install R
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

  # 2c - Install packages and dependencies needed
      - name: install packages
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::tidyverse
            any::quantmod

  # 2d - Run script
      - name: render rmd
        run: rmarkdown::render("scripts/tidyverse.Rmd")
        shell: Rscript {0}

  # 2e - Add new file, commit and push (git add data/*)
  - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"

